package vistas;

import entidades.Empleado;
import entidades.Empresa;
import java.awt.Graphics;
import vistas.VistaMostrar;
import java.util.ArrayList;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**

 * @author juanj
 */
public class principal extends javax.swing.JFrame {
        public Empleado e1 = null;
        public static ArrayList<Empleado> listaEmp = new ArrayList<Empleado>(); //todes los empleados
        public int k=0,j=0;
        public Empresa emp = null;
        public static ArrayList<Empresa> empresas = new ArrayList<Empresa>(); // todas las que Existen

    public static ArrayList<Empleado> getListaEmp() {  return listaEmp;    }
    public static ArrayList<Empresa> getEmpresas() {   return empresas;   }
      
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        BtGuardaEmpleado.setEnabled(false); 
        btnMostrarEmp.setEnabled(false);   
    }

    /*  private static Image IMG=new ImageIcon(getClass().getResource("img/logojsivet.png")).getImage();

        public void paintChildren(Graphics g){
            g.drawImage(IMG, 0, 0, getWidth(), getHeight(), this);
            super.paintChildren(g);
        }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        ImageIcon icono = new ImageIcon(getClass().getResource("/image/colores.jpg"));
        Image miImagen = icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        pnlEmpresa = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtGuardaEmpresa = new javax.swing.JButton();
        jTFRazon = new javax.swing.JTextField();
        jTFCUIT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnMostrarEmp = new javax.swing.JButton();
        pnlEmpleado = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        BtGuardaEmpleado = new javax.swing.JButton();
        jTFDni = new javax.swing.JTextField();
        jTFnombre = new javax.swing.JTextField();
        jTFApe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFSueldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jComboBoxEmpresa = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemMostrar = new javax.swing.JMenuItem();
        mnuListar = new javax.swing.JMenuItem();
        abrirVentana = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuEmpmaySueldo = new javax.swing.JMenuItem();
        jMenuListado = new javax.swing.JMenuItem();
        jMenuPromedio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        escritorio.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1219, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Cree una empresa"));
        pnlEmpresa.setName("panelEmpresa"); // NOI18N

        jLabel11.setText("Razon Social");

        BtGuardaEmpresa.setText("Crear Empresa");
        BtGuardaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardaEmpresaActionPerformed(evt);
            }
        });

        jTFRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRazonActionPerformed(evt);
            }
        });

        jTFCUIT.setName("jTFNom"); // NOI18N

        jLabel13.setText("CUIT");

        btnMostrarEmp.setText("Mostrar Empleados del Combo");
        btnMostrarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmpresaLayout = new javax.swing.GroupLayout(pnlEmpresa);
        pnlEmpresa.setLayout(pnlEmpresaLayout);
        pnlEmpresaLayout.setHorizontalGroup(
            pnlEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtGuardaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(pnlEmpresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMostrarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpresaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpresaLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(35, 35, 35)
                            .addComponent(jTFRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmpresaLayout.setVerticalGroup(
            pnlEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpresaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtGuardaEmpresa)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarEmp)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlEmpleado.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese sus datos"));
        pnlEmpleado.setName("panelEmpleado"); // NOI18N

        lblDni.setText("Documento");

        BtGuardaEmpleado.setText("Guardar");
        BtGuardaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardaEmpleadoActionPerformed(evt);
            }
        });

        jTFDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDniActionPerformed(evt);
            }
        });

        jTFnombre.setName("jTFNom"); // NOI18N

        jTFApe.setName("jTFApe"); // NOI18N

        jLabel2.setText("Sueldo");

        jTFSueldo.setName("jTFSueldo"); // NOI18N

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Categoria");

        jComboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Vendedor", "Repositor", "Administrativo" }));
        jComboBoxCat.setSelectedIndex(-1);
        jComboBoxCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCatActionPerformed(evt);
            }
        });

        jLabel12.setText("Empresas -->");

        javax.swing.GroupLayout pnlEmpleadoLayout = new javax.swing.GroupLayout(pnlEmpleado);
        pnlEmpleado.setLayout(pnlEmpleadoLayout);
        pnlEmpleadoLayout.setHorizontalGroup(
            pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFApe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDni)
                        .addGap(35, 35, 35)
                        .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEmpleadoLayout.createSequentialGroup()
                        .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtGuardaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSueldo)
                            .addComponent(jComboBoxCat, 0, 139, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlEmpleadoLayout.setVerticalGroup(
            pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpleadoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(BtGuardaEmpleado)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("Empleado");

        jMenuItemMostrar.setText("Mostrar");
        jMenuItemMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMostrar);

        mnuListar.setText("Listados");
        jMenu1.add(mnuListar);

        abrirVentana.setText("Menu abrir");
        abrirVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirVentanaActionPerformed(evt);
            }
        });
        jMenu1.add(abrirVentana);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Empresa");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Sueldo");

        jMenuEmpmaySueldo.setText("Emp mayor Sueldo");
        jMenuEmpmaySueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpmaySueldoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuEmpmaySueldo);

        jMenuListado.setText("ListaEmp supera sueldo base");
        jMenu4.add(jMenuListado);

        jMenuPromedio.setText("sueldo promedio ");
        jMenu4.add(jMenuPromedio);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Salir");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlEmpresa.getAccessibleContext().setAccessibleName("Empresa Nueva");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void jTFDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDniActionPerformed

    private void BtGuardaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardaEmpleadoActionPerformed
        if (validarCamposVacios(pnlEmpleado)) {
          e1 = new Empleado(Integer.parseInt(jTFDni.getText()), jTFnombre.getText(), jTFApe.getText(), jComboBoxCat.getSelectedItem().toString(), Double.parseDouble(jTFSueldo.getText()));
          for(int i=0; i<empresas.size(); i++){
            if(empresas.get(i).getRazonSocial() == jComboBoxEmpresa.getSelectedItem().toString()){
                e1.setTrabaja(empresas.get(i));  // toda la empresa
                JOptionPane.showMessageDialog(rootPane, "trabaja en "+e1.getTrabaja().getRazonSocial());
                
                empresas.get(i).agregaEmpleado(e1);
                JOptionPane.showMessageDialog(rootPane, "añadido a la empresas "+empresas.get(i).getRazonSocial());
                
            }
          }
          if(!listaEmp.contains(e1)) listaEmp.add(e1); 
          //limpiarEmpleado();       //opcion1
          vaciarCampos(pnlEmpleado); //opcion2 THE BEST!
        } else
            JOptionPane.showMessageDialog(pnlEmpleado, "Los campos no deben estar vacios!...");
    }//GEN-LAST:event_BtGuardaEmpleadoActionPerformed

    private void jTFRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRazonActionPerformed

    private void BtGuardaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardaEmpresaActionPerformed
        if (validarCamposVacios(pnlEmpresa)) {
            emp = new Empresa();
            emp.setRazonSocial(jTFRazon.getText()); 

            emp.setCUIT(Integer.parseInt(jTFCUIT.getText()));
            //emp.setListaEmpleado(null);
             if(!empresas.contains(emp)){
                 empresas.add(emp);
                 System.out.println("agregado!");
                 jComboBoxEmpresa.addItem(emp.getRazonSocial());
                 btnMostrarEmp.setEnabled(true);
             }else
                 JOptionPane.showMessageDialog(pnlEmpresa,"La empresa ya existe!!");
            BtGuardaEmpleado.setEnabled(true);
            vaciarCampos(pnlEmpresa); //opcion2 THE BEST!
        }else
            JOptionPane.showMessageDialog(pnlEmpresa, "Los campos no deben estar vacios!...");
    }//GEN-LAST:event_BtGuardaEmpresaActionPerformed

    private void btnMostrarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpActionPerformed
        for(int i=0; i<empresas.size(); i++){
            if(empresas.get(i).getRazonSocial() == jComboBoxEmpresa.getSelectedItem().toString()){
                empresas.get(i).mostrarEmp();
            }
        }   
    }//GEN-LAST:event_btnMostrarEmpActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
         // dispose();
            System.exit(0);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaMostrar vm = new VistaMostrar();
        escritorio.add(vm);
        vm.setVisible(true);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_jMenuItemMostrarActionPerformed

    private void jMenuEmpmaySueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpmaySueldoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        vista2 v2 = new vista2();
        escritorio.add(v2);
        v2.setVisible(true);
        escritorio.moveToFront(v2);
    }//GEN-LAST:event_jMenuEmpmaySueldoActionPerformed

    private void abrirVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirVentanaActionPerformed
        // TODO add your handling code here:
        nuevaVentana nueva = new nuevaVentana();
        nueva.setTitle("Soy un Internal Frame");
        escritorio.add(nueva);
        nueva.setVisible(true);
    }//GEN-LAST:event_abrirVentanaActionPerformed

    private void jComboBoxCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCatActionPerformed
    //El método regresa true si todos los campos estan llenos 
//false si alguno esta vacio 
    public boolean validarCamposVacios(JPanel jPanel){
     boolean flag=true;
     for(int i=0; i<jPanel.getComponents().length;i++){
        if(!flag) break;
        if(jPanel.getComponents()[i]instanceof JTextField){
           flag=!((JTextField)jPanel.getComponents()[i]).getText().equals("") ? true : false;             
        }
     }
    return flag;
   } 
    public void vaciarCampos(JPanel jPanel){
        JComboBox combo = null;
        for(int i=0; i<jPanel.getComponents().length;i++){
            if(jPanel.getComponents()[i]instanceof JTextField){
               JTextField caja=(JTextField)jPanel.getComponents()[i];     
               caja.setText(null);
            }
            if(jPanel.getComponents()[i]instanceof JComboBox){
                combo =(JComboBox)jPanel.getComponents()[i];
                combo.setSelectedIndex(-1);
            }
       }
    } 
    
    private void limpiarEmpresa(){
        jTFRazon.setText("");
        jTFCUIT.setText("");
    }
    private void limpiarEmpleado(){
        jTFDni.setText("");
        jTFnombre.setText("");
        jTFApe.setText("");
        jComboBoxCat.setSelectedIndex(-1);
        jTFSueldo.setText("");
        jComboBoxEmpresa.setSelectedIndex(-1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGuardaEmpleado;
    private javax.swing.JButton BtGuardaEmpresa;
    private javax.swing.JMenuItem abrirVentana;
    private javax.swing.JButton btnMostrarEmp;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private javax.swing.JComboBox<String> jComboBoxEmpresa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEmpmaySueldo;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemMostrar;
    private javax.swing.JMenuItem jMenuListado;
    private javax.swing.JMenuItem jMenuPromedio;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTFApe;
    private javax.swing.JTextField jTFCUIT;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFRazon;
    private javax.swing.JTextField jTFSueldo;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JLabel lblDni;
    private javax.swing.JMenuItem mnuListar;
    private javax.swing.JPanel pnlEmpleado;
    private javax.swing.JPanel pnlEmpresa;
    // End of variables declaration//GEN-END:variables
}
