package vistas;

import entidades.Empleado;
import entidades.Empresa;
import java.util.ArrayList;
import vistas.principal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanj
 */
public final class VistaMostrar extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo= new DefaultTableModel(){
        public boolean isCellEditable(int fila,int col){
           return false;
        }
    };
    
    public VistaMostrar() {
        initComponents();
        armaCabeceraTabla();
        cargaEmpresas();
        cargaTabla();
    }
    public void armaCabeceraTabla(){
      //Titulos de Columnas
        ArrayList<Object> columnas=new ArrayList<Object>();
        columnas.add("DNI");
        columnas.add("nombre");
        columnas.add("apellido");
        columnas.add("categoria");
        columnas.add("sueldo");
        tEmpleados.setModel(modelo);
        
        for(Object it:columnas){
           modelo.addColumn(it);
        }
        tEmpleados.setModel(modelo);
  }
    public void borraFilasTabla(){
         int a =modelo.getRowCount()-1;
            for(int i=a;i>=0;i--){
                modelo.removeRow(i );
            }
      }
    public void cargaEmpresas(){
        //Carga empresas al ComboBox
         for(Empresa emp: principal.getEmpresas())
                cboEmpresas.addItem(emp);
    }
    public void cargaTabla(){
        borraFilasTabla();
         //Obtengo la Empresa q esta seleccionada en el ComboBox
            Empresa emp=(Empresa)cboEmpresas.getSelectedItem();
        //Llenar filas
        for(Empleado e: principal.getListaEmp()){
          //Comparo por los id o sobreescribo el método equals en Materias
            if(e.getTrabaja().getRazonSocial()==emp.getRazonSocial()){
                modelo.addRow(new Object[]{e.getDocumento(), e.getNombre(),e.getApellido(), e.getCategoria(), e.getSueldo()});
            }           
        }       
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tEmpleados = new javax.swing.JTable();
        jbtSalida = new javax.swing.JButton();
        jbtVolver = new javax.swing.JButton();
        cboEmpresas = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mostrar Empleados");

        tEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tEmpleados);

        jbtSalida.setText("Salida");
        jbtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalidaActionPerformed(evt);
            }
        });

        jbtVolver.setText("Volver");
        jbtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVolverActionPerformed(evt);
            }
        });

        cboEmpresas.setBackground(new java.awt.Color(255, 102, 102));
        cboEmpresas.setForeground(new java.awt.Color(0, 0, 0));
        cboEmpresas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEmpresasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtSalida)
                        .addGap(18, 18, 18)
                        .addComponent(jbtVolver)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cboEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalidaActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null,"¿Realmente Desea Salir del programa?","Confirmar Salida",JOptionPane.WARNING_MESSAGE);
        System.out.println("i"+i);
        if (i==0) System.exit(0);

    }//GEN-LAST:event_jbtSalidaActionPerformed

    private void jbtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtVolverActionPerformed

    private void cboEmpresasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEmpresasItemStateChanged
        cargaTabla();
    }//GEN-LAST:event_cboEmpresasItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Empresa> cboEmpresas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtSalida;
    private javax.swing.JButton jbtVolver;
    private javax.swing.JTable tEmpleados;
    // End of variables declaration//GEN-END:variables
}
